//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURO
    {
        public SEGURO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public string ID_SEGURO { get; set; }
        public int VALOR { get; set; }
        public string ACTIVO { get; set; }
        public string COBERTURA_ID_COBERTURA { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual COBERTURA COBERTURA { get; set; }
    }
}
